{% set name = "lightning-utilities" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lightning-utilities-{{ version }}.tar.gz
  sha256: 5002eaadfb8caa2cd2bb7b845748d4e8e77ac275137b66b10182db3ecb0e4867

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - packaging >=17.1
    - typing_extensions

test:
  imports:
    - lightning_utilities
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Lightning-AI/utilities
  summary: PyTorch Lightning Sample project.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Borda
    - carmocca
    - Tobias-Fischer
