{% set name = "lightning-utilities" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3e934ae9c2a77e2f617a4377750e2564d614c391445368d2116a2efe70143ebc

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - packaging >=17.1
    - typing_extensions
    - setuptools

test:
  imports:
    - lightning_utilities
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}


about:
  home: https://github.com/Lightning-AI/utilities
  summary: PyTorch Lightning Sample project.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Borda
    - carmocca
    - Tobias-Fischer
