{% set name = "lightning-utilities" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lightning-utilities-{{ version }}.tar.gz
  sha256: d769ab9b76ebdee3243d1051d509aafee57d7947734ddc22977deef8a6427f2f

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - fire >=0.4

test:
  imports:
    - lightning_utilities
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Lightning-AI/utilities
  summary: PyTorch Lightning Sample project.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Borda
    - carmocca
    - Tobias-Fischer
